### PR TITLE
Replace ToolBuilder.build() exceptions with Result type

### LINKED ISSUE #492: Replace throw with Result[A] in tool creation methods
## Problem                                                                                                                        
                                                                                                                                  
  Tool creation methods such as `ToolBuilder.build()` and `ToolRegistry.getToolDefinitions()` currently throw exceptions on invalid 
  input instead of returning `Result[A]`.                                                                                           
                                                                                                                                    
```                                                                                                           
  // ToolFunction.scala:112                                                                                                         
  throw new IllegalStateException("Handler not defined")

  // ToolRegistry.scala:123
  throw new IllegalArgumentException(s"Unsupported LLM provider: $provider")
```

However, the project's contribution guidelines (CLAUDE.md) explicitly state:

  Core Principle #1: Use Result[A] instead of exceptions — type Result[+A] = Either[LLMError, A]

  Additionally:
  - Scalafix rules ban try/catch/finally in core code
  - Throwing exceptions here forces callers to use exactly what is disallowed

  Every other creation/validation API in the codebase already follows the Result convention:
  - Llm4sConfig.provider()
  - ApiKey.apply()
  - ModelName.apply()
  - ToolName.create()
  - Url.create()
  - ConversationId.create()
  - CompressionTarget.create()

  Tool creation is currently the only exception to this rule.

  Expected Behavior

  build() and all related factory methods should return Result[ToolFunction[...]], allowing callers to compose them using
  for-comprehensions like every other fallible operation in the library:

 ```
 for {
    providerConfig <- Llm4sConfig.provider()
    client         <- LLMConnect.getClient(providerConfig)
    braveConfig    <- Llm4sConfig.loadBraveSearchTool()
    braveTool      <- BraveSearchTool.create(braveConfig)
  } yield new ToolRegistry(Seq(braveTool))

```
  This keeps the API:
  - Consistent with every other fallible operation in the library
  - Type-safe with errors tracked in the return type
  - Composable via standard for-comprehensions
  - Aligned with project guidelines and Scalafix rules

  Task List

- [ ]   PR 1: Convert ToolBuilder.build() to return Result + update all built-in tools, BuiltinTools, and core tests (~15 production
files, ~11 test files)
- [ ]   PR 2: Convert ToolRegistry.getToolDefinitions() to return Result + update AzureToolHelper and related tests (~3 files)
- [ ]   PR 3: Workspace module — update WorkspaceTools.scala factory methods to return Result (~2 files)
- [ ]   PR 4: Update all samples to properly handle Result (~6 files)
- [ ]   PR 5: Fix ShellTool re-throw behavior + clean up scaladoc throw examples (~3 files)

  PR 1 must merge first. PRs 2–5 are independent of each other after that.

### PR DESCRIPTION
**Pull request by im-vedant**
This pull request refactors the tool creation and initialization logic throughout the codebase to use a `Result` type for improved error handling and composability, instead of returning raw tool instances or sequences. This change affects tool builders, built-in tool aggregators, agent initialization, and agent handoff tool creation. The result is more robust error propagation and safer tool registry construction, especially in scenarios involving optional or dynamically composed tools.

Tool creation and error handling improvements:

* Changed the `ToolBuilder.build()` method and all built-in tool definitions (e.g., `CalculatorTool`, `DateTimeTool`, `UUIDTool`, `JSONTool`) to return a `Result` type, enabling explicit error propagation during tool construction. [[1]](diffhunk://#diff-06f196b883e18d907529186e7b5f4e5e2f72dd07558fda47db1ae9e85ef15477L110-R114) [[2]](diffhunk://#diff-72d58ff8b883fc49b317b63f5bfce8b9177c0c5b2bb6db1824ad59c6cca6c597L66-R67) [[3]](diffhunk://#diff-1ede819cb8ff9ea2339f7231ae82acad7596a517d1723f1d94c97cddf18d5df8L78-R79) [[4]](diffhunk://#diff-1f9726787554a96901f82bcc85987f0786b91299d8ad8311378870dbe0b1f102L70-R71) [[5]](diffhunk://#diff-b1ae42a5774fcce42493cb736e80c6d20246f0204cdc59c7e90697e481653acbL65-R66)
* Updated the `BuiltinTools` and `core.allTools` aggregators to compose tool lists using `for` comprehensions on `Result`, ensuring that any tool creation failure is handled gracefully and prevents partial tool registry creation. [[1]](diffhunk://#diff-5cacfb7045a620c6fe147a39f4bcd7ca815faad2a12ee33fd4664b9db91accc5L43-R53) [[2]](diffhunk://#diff-5cacfb7045a620c6fe147a39f4bcd7ca815faad2a12ee33fd4664b9db91accc5L62-R70) [[3]](diffhunk://#diff-5cacfb7045a620c6fe147a39f4bcd7ca815faad2a12ee33fd4664b9db91accc5L81-R91) [[4]](diffhunk://#diff-5cacfb7045a620c6fe147a39f4bcd7ca815faad2a12ee33fd4664b9db91accc5L106-R111) [[5]](diffhunk://#diff-5cacfb7045a620c6fe147a39f4bcd7ca815faad2a12ee33fd4664b9db91accc5L139-R174) [[6]](diffhunk://#diff-0855fdff2a918a67c3ed64134e37cd10ceca44c78dfc0893ac0ab0af173a3f00L31-R36)

Agent initialization and handoff logic:

* Refactored the `Agent.initialize` and `Agent.createHandoffTools` methods to return `Result` types, and updated all call sites to handle errors using for comprehensions and flatMap, ensuring agent initialization fails early and cleanly on tool creation errors. [[1]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781L106-R106) [[2]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781L127-R129) [[3]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781R141) [[4]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781L454-R464) [[5]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781R488-R489) [[6]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781L950-R958) [[7]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781L1185-R1193) [[8]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781R1224) [[9]](diffhunk://#diff-ba71e3bb871bccc7a160556ad07c591e4bee6f18d9993a2e96307a781f5ab781L1625-R1633)
* Updated `AssistantAgent.addUserMessage` to propagate agent initialization errors as `AssistantError.SessionError`, improving error reporting in session management.

Documentation and API usage:

* Updated usage examples and documentation in `BuiltinTools` to demonstrate the new error-aware tool registry construction pattern using `for` comprehensions.

These changes make tool initialization safer and more robust, with clear error handling and propagation throughout the agent and assistant workflow.

fixes #492

### CODE REVIEW

File: modules/core/src/test/scala/org/llm4s/agent/AgentSpec.scala [hunk 1]
```diff
@@ -137,6 +137,8 @@ class AgentSpec extends AnyFlatSpec with Matchers {
         CalculatorResult(result)
       }
     }.build()
+      .toOption
+      .get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/agent/AgentSpec.scala]: What? toOption.get ?

`.get` is banned totally! And `.get` is Dangerous and totally violates the core-purpose of the `Option` Monad

File: modules/core/src/main/scala/org/llm4s/agent/Agent.scala [hunk 2]
```diff
@@ -103,8 +103,8 @@ class Agent(client: LLMClient) {
     handoffs: Seq[Handoff] = Seq.empty,
     systemPromptAddition: Option[String] = None,
     completionOptions: CompletionOptions = CompletionOptions()
-  ): AgentState = {
-    val baseSystemPrompt = """You are a helpful assistant with access to tools. 
+  ): Result[AgentState] = {
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/agent/Agent.scala:147]: Breaking API: return type changed from value to Result and this can break user code silently.
Please keep old method as deprecated wrapper for one release and add clear migration path.
Principle: Public API changes must be backward compatible or intentionally versioned with migration support.

File: modules/core/src/main/scala/org/llm4s/toolapi/builtin/BuiltinTools.scala [hunk 3]
```diff
@@ -40,12 +45,12 @@ object BuiltinTools {
    * - UUIDTool: Generate UUIDs
    * - JSONTool: Parse/format/query JSON
    */
-  def core: Seq[ToolFunction[_, _]] = Seq(
-    DateTimeTool.tool,
-    CalculatorTool.tool,
-    UUIDTool.tool,
-    JSONTool.tool
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/toolapi/builtin/BuiltinTools.scala:47]: Breaking API: BuiltinTools methods now return Result and downstream code using Seq will fail compile.
Add compatibility helpers or deprecated old signatures before merge.
Principle: Stable library contracts are mandatory for safe upgrades.

File: modules/core/src/main/scala/org/llm4s/assistant/AssistantAgent.scala [hunk 4]
```diff
@@ -296,21 +296,26 @@ class AssistantAgent(
...
+        val updatedAgentState = agentState
+          .addMessage(UserMessage(query))
+          .withStatus(AgentStatus.InProgress)
+        Right(state.withAgentState(updatedAgentState))
+      case None =>
+        // First message - initialize agent
+        agent
+          .initialize(query, tools)
+          .map(state.withAgentState)
+          .leftMap(llmError =>
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/assistant/AssistantAgent.scala:319]: Typed llm error is flattened to plain text here, so root cause data gets lost for debug.
Wrap original error inside AssistantError instead of only string message.
Principle: Keep error information structured and preserve cause chain.

File: modules/core/src/main/scala/org/llm4s/agent/Agent.scala [hunk 5]
```diff
@@ -451,33 +454,38 @@ class Agent(client: LLMClient) {
...
+          ).withHandler { extractor =>
+            extractor.getString("reason").map { reason =>
+              HandoffResult(
+                handoff_requested = true,
+                handoff_id = handoff.handoffId,
+                reason = reason
+              )
+            }
+          }.build()
         }
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/agent/Agent.scala:579]: This append in foldLeft gives O(n^2) list building when handoffs increase.
Use prepend and reverse once, or a builder, to keep linear complexity.
Principle: Avoid avoidable quadratic work in core execution paths.

File: modules/samples/src/main/scala/org/llm4s/samples/toolapi/BuiltinToolsExample.scala [hunk 6]
```diff
@@ -122,142 +127,170 @@ object BuiltinToolsExample {
...
-      case Right(result) => logger.info("File info: {}", result.render(indent = 2))
-      case Left(error)   => logger.error("File info failed: {}", error)
+    } yield {
+      val registry = new ToolRegistry(tools)
+
+      // List directory
+      logger.info("Listing /tmp directory...")
+      registry.execute(
+        ToolCallRequest(
+          functionName = "list_directory",
```
Comment (vim89) [inline modules/samples/src/main/scala/org/llm4s/samples/toolapi/BuiltinToolsExample.scala:142]: Wrong parameter key: list_directory expects max_entries but sample sends limit.
Please change to max_entries so sample result is predictable.
Principle: Samples must be correct and runnable as documentation.

File: modules/core/src/test/scala/org/llm4s/agent/AgentSpec.scala [hunk 7]
```diff
@@ -150,7 +152,7 @@ class AgentSpec extends AnyFlatSpec with Matchers {
     val mockClient = new MockLLMClient()
     val agent      = new Agent(mockClient)
 
-    val state = agent.initialize("What is 2+2?", testTools)
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/agent/AgentSpec.scala:153]: Unsafe unwrap added with toOption.get; this can hide real failure and crash with NoSuchElementException.
Use fold/match and fail with clear message including error details.
Principle: Tests must fail with explicit intent, never by unsafe Option unwrap.

File: modules/core/src/test/scala/org/llm4s/toolapi/ToolFunctionSpec.scala [hunk 8]
```diff
@@ -39,7 +42,7 @@ class ToolFunctionSpec extends AnyFlatSpec with Matchers {
       "ping",
       "Returns success without parameters",
       schema
-    ).withHandler(_ => Right(EmptyResult(success = true))).build()
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/ToolFunctionSpec.scala:42]: Unsafe get in builder result makes test brittle and masks left branch diagnostics.
Use explicit pattern match and assert on Left/Right message.
Principle: Keep test assertions deterministic and error aware.

File: modules/core/src/test/scala/org/llm4s/toolapi/builtin/CoreToolsSpec.scala [hunk 9]
```diff
@@ -9,7 +9,7 @@ class CoreToolsSpec extends AnyFlatSpec with Matchers {
 
   "DateTimeTool" should "return current date/time in default timezone" in {
     val params = ujson.Obj()
-    val result = DateTimeTool.tool.handler(SafeParameterExtractor(params))
+    val result = DateTimeTool.tool.toOption.get.handler(SafeParameterExtractor(params))
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/builtin/CoreToolsSpec.scala]: Multiple toOption.get usages were added here and can crash instead of giving clean assertion output.
Prefer helper that unwraps with fail(error.formatted) for readability and safety.
Principle: Test setup should never use partial unsafe operations.

File: modules/core/src/test/scala/org/llm4s/toolapi/builtin/FileSystemToolsSpec.scala [hunk 10]
```diff
@@ -66,7 +66,7 @@ class FileSystemToolsSpec extends AnyFlatSpec with Matchers {
 
     // No blocked paths, only test dir allowed
     val config = FileConfig(allowedPaths = Some(Seq(testDir.toString)), blockedPaths = Seq.empty)
-    val tool   = ReadFileTool.create(config)
+    val tool   = ReadFileTool.create(config).toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/builtin/FileSystemToolsSpec.scala]: Unsafe get here can convert validation failure into runtime crash in test.
Replace with explicit Right assertion and clear failure message.
Principle: Expected error paths must stay explicit even in tests.

File: modules/core/src/test/scala/org/llm4s/toolapi/builtin/HttpToolsSpec.scala [hunk 11]
```diff
@@ -59,7 +59,7 @@ class HttpToolsSpec extends AnyFlatSpec with Matchers {
 
   "HTTPTool" should "reject blocked domains" in {
     val config = HttpConfig()
-    val tool   = HTTPTool.create(config)
+    val tool   = HTTPTool.create(config).toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/builtin/HttpToolsSpec.scala]: Unsafe get on tool creation can hide why creation failed under config change.
Match on result and print exact error in fail path.
Principle: Preserve diagnosability when asserting constructor results.

File: modules/core/src/test/scala/org/llm4s/toolapi/builtin/ShellToolsSpec.scala [hunk 12]
```diff
@@ -76,7 +76,7 @@ class ShellToolsSpec extends AnyFlatSpec with Matchers {
   "ShellTool" should "execute allowed commands" in {
     assume(!isWindows, "Unix shell commands not available on Windows")
     val config = ShellConfig(allowedCommands = Seq("echo", "pwd"))
-    val tool   = ShellTool.create(config)
+    val tool   = ShellTool.create(config).toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/builtin/ShellToolsSpec.scala]: Unsafe unwrap added for shell tool creation; failure reason is lost.
Use result.fold(err => fail(err), tool => ...) pattern.
Principle: Do not drop domain errors by partial unwrapping.

File: modules/core/src/test/scala/org/llm4s/toolapi/builtin/BuiltinToolsSpec.scala [hunk 13]
```diff
@@ -6,7 +6,7 @@ import org.scalatest.matchers.should.Matchers
 class BuiltinToolsSpec extends AnyFlatSpec with Matchers {
 
   "BuiltinTools.core" should "include all core utilities" in {
-    val tools = BuiltinTools.core
+    val tools = BuiltinTools.core.toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/builtin/BuiltinToolsSpec.scala]: Unsafe get here repeats across file and can hide contract breakages.
Create small helper to unwrap Result with descriptive fail once.
Principle: Reduce repeated unsafe patterns and centralize assertion logic.

File: modules/core/src/test/scala/org/llm4s/mcp/MCPServerSpec.scala [hunk 14]
```diff
@@ -24,7 +24,7 @@ class MCPServerSpec extends AnyFunSpec with Matchers with BeforeAndAfterAll {
       "ping",
       "Echoes a message",
       pingSchema
-    ).withHandler(pingHandler).build()
+    ).withHandler(pingHandler).build().toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/mcp/MCPServerSpec.scala]: Unsafe toOption.get on tool build can make MCP tests flaky on schema validation changes.
Use explicit result match and fail with error text.
Principle: Tests should expose domain failure, not generic unwrap exceptions.

File: modules/core/src/test/scala/org/llm4s/mcp/MCPToolRegistryCacheSpec.scala [hunk 15]
```diff
@@ -35,7 +35,7 @@ class MCPToolRegistryCacheSpec extends AnyFlatSpec with Matchers {
       "test_tool",
       "A test tool",
       schema
-    ).withHandler(_ => Right(TestResult("result"))).build()
+    ).withHandler(_ => Right(TestResult("result"))).build().toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/mcp/MCPToolRegistryCacheSpec.scala]: Unsafe unwrap here drops valuable context when tool creation fails.
Match Result and keep failure message explicit.
Principle: Keep debug signal high by avoiding partial getters.

File: modules/core/src/test/scala/org/llm4s/toolapi/GameToolsIntegrationTest.scala [hunk 16]
```diff
@@ -72,7 +72,7 @@ class GameToolsIntegrationTest extends AnyFlatSpec with Matchers with BeforeAndA
         "list_inventory",
         "List all items currently in the player's inventory",
         listInventorySchema
-      ).withHandler(listInventoryHandler).build()
+      ).withHandler(listInventoryHandler).build().toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/GameToolsIntegrationTest.scala]: Unsafe unwrap pattern repeated in integration test setup.
Replace with helper that fails with the actual left error text.
Principle: Integration tests must report root cause clearly.

File: modules/core/src/test/scala/org/llm4s/toolapi/ZeroParameterToolTest.scala [hunk 17]
```diff
@@ -92,13 +94,13 @@ class ZeroParameterToolTest extends AnyFlatSpec with Matchers {
       "get_status",
       "Returns the player's current status",
       Schema.`object`[Map[String, Any]]("No parameters required")
-    ).withHandler(_ => Right(StatusResult(health = 100, mana = 50))).build()
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/ZeroParameterToolTest.scala:95]: toOption.get added here can hide handler build failures.
Use explicit Right assertion before executing tool.
Principle: Never bypass typed error channels in tests.

File: modules/core/src/test/scala/org/llm4s/toolapi/builtin/search/BraveSearchToolSpec.scala [hunk 18]
```diff
@@ -48,7 +48,7 @@ class BraveSearchToolSpec extends AnyFlatSpec with Matchers {
           expectedName: String,
           expectedDescription: String
         ): Unit = {
-          val tool = BraveSearchTool.create(config, category)
+          val tool = BraveSearchTool.create(config, category).toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/builtin/search/BraveSearchToolSpec.scala]: Unsafe get added in search tool spec and can fail with low quality stacktrace.
Handle Result explicitly and fail with formatted message.
Principle: Test failures should be actionable from first line.

File: modules/core/src/test/scala/org/llm4s/toolapi/builtin/search/DuckDuckGoSearchToolSpec.scala [hunk 19]
```diff
@@ -27,7 +27,7 @@ class DuckDuckGoSearchToolSpec extends AnyFlatSpec with Matchers {
 
   "DuckDuckGoSearchTool" should "have the correct metadata" in {
     val toolConfig = DuckDuckGoSearchToolConfig(apiUrl = "https://api.duckduckgo.com")
-    val tool       = DuckDuckGoSearchTool.create(toolConfig)
+    val tool       = DuckDuckGoSearchTool.create(toolConfig).toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/builtin/search/DuckDuckGoSearchToolSpec.scala]: Unsafe get on tool creation weakens this spec error reporting.
Use fold/match and include exact creation error in assertion failure.
Principle: Keep assertions informative, not exception driven.

File: modules/core/src/main/scala/org/llm4s/toolapi/builtin/core/package.scala [hunk 20]
```diff
@@ -28,10 +28,10 @@ package object core {
   /**
    * All core utility tools combined into a sequence.
    */
-  val allTools: Seq[org.llm4s.toolapi.ToolFunction[_, _]] = Seq(
-    DateTimeTool.tool,
-    CalculatorTool.tool,
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/toolapi/builtin/core/package.scala:33]: This file moved API to Result, but the examples in same Scaladoc block still show direct ToolFunction usage.

Please update examples to Result handling so copy paste works without confusion.

Principle: Documentation must compile with current public types.

File: modules/core/src/main/scala/org/llm4s/toolapi/builtin/filesystem/package.scala [hunk 21]
```diff
@@ -61,9 +61,9 @@ package object filesystem {
   /**
    * All file system tools with default configuration (read-only, excludes write).
    */
-  val readOnlyTools: Seq[org.llm4s.toolapi.ToolFunction[_, _]] = Seq(
-    ReadFileTool.tool,
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/toolapi/builtin/filesystem/package.scala:65]: Same concern for this package docs: code examples still look pre-Result while API now returns Result values.

Please align examples with current signatures to avoid broken onboarding.\nPrinciple: Samples and docs are executable contract for users.

File: modules/core/src/main/scala/org/llm4s/toolapi/builtin/http/package.scala [hunk 22]
```diff
@@ -46,7 +46,6 @@ package object http {
   /**
    * All HTTP tools with default configuration.
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/toolapi/builtin/http/package.scala:57]: HTTP package docs also need update after Result return type migration in this file.\nPlease change snippets to explicit Result flow to prevent user copy errors.\nPrinciple: Keep docs and implementation in lockstep after API changes.

File: modules/core/src/test/scala/org/llm4s/agent/AgentSpec.scala (hunk 1 above)
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/agent/AgentSpec.scala]: What? Option.get?

`.get` is banned totally! This is dangerous, this violates the core-purpose of `Option` Monad

File: modules/core/src/main/scala/org/llm4s/assistant/AssistantAgent.scala [hunk 23]
```diff
@@ -296,21 +296,26 @@ class AssistantAgent(
...
+          .withStatus(AgentStatus.InProgress)
+        Right(state.withAgentState(updatedAgentState))
+      case None =>
+        // First message - initialize agent
+        agent
+          .initializeSafe(query, tools)
+          .map(state.withAgentState)
+          .leftMap(llmError =>
+            AssistantError.SessionError(
+              s"Agent initialization failed: ${llmError.message}",
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/assistant/AssistantAgent.scala:321]: Follow-up: this still drops structured error context from `LLMError` into plain text. Please preserve original cause/typed details in AssistantError so debugging has full signal. Principle: keep error information structured and preserve cause chain.

File: modules/core/src/main/scala/org/llm4s/agent/Agent.scala [hunk 24]
```diff
@@ -440,33 +467,38 @@ class Agent(client: LLMClient) {
...
+              HandoffResult(
+                handoff_requested = true,
+                handoff_id = handoff.handoffId,
+                reason = reason
+              )
+            }
+          }.buildSafe()
         }
-      }.build()
+      } yield tools :+ tool
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/agent/Agent.scala]: Follow-up: this quadratic append is still present in latest head (`tools :+ tool` inside fold). Please switch to prepend + reverse once, or a builder, to keep it linear. Principle: avoid avoidable quadratic work in core execution paths.

File: modules/samples/src/main/scala/org/llm4s/samples/toolapi/BuiltinToolsExample.scala [hunk 25]
```diff
@@ -122,142 +127,170 @@ object BuiltinToolsExample {
...
+          arguments = ujson.Obj("path" -> "/tmp", "limit" -> 5)
```
Comment (vim89) [inline modules/samples/src/main/scala/org/llm4s/samples/toolapi/BuiltinToolsExample.scala]: Follow-up: sample still passes `limit`, but tool schema expects `max_entries`. This will confuse users copying the example. Principle: samples must be correct and runnable as documentation.

File: modules/core/src/main/scala/org/llm4s/agent/Agent.scala [hunk 26]
```diff
@@ -440,33 +467,38 @@ class Agent(client: LLMClient) {
...
-            handoff_requested = true,
-            handoff_id = handoff.handoffId,
-            reason = reason
-          )
+    handoffs.foldLeft[Result[Seq[ToolFunction[_, _]]]](Right(Seq.empty)) { (acc, handoff) =>
+      for {
+        tools <- acc
+        tool <- {
+          val toolName        = handoff.handoffId
+          val toolDescription = s"Hand off this query to a specialist agent. ${handoff.transferReason.getOrElse("")}"
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/agent/Agent.scala]: This uses `getOrElse` on an Option inside hot-path tool construction. Please prefer explicit Option transformation flow so fallback behavior stays visible and composable. Principle: prefer total monadic transformations over fallback unwrapping.

File: modules/core/src/main/scala/org/llm4s/toolapi/builtin/filesystem/ListDirectoryTool.scala [hunk 27]
```diff
@@ -104,12 +105,32 @@ object ListDirectoryTool {
         includeHidden = extractor.getBoolean("include_hidden").toOption.getOrElse(false)
```
Comment (vim89) [inline modules/core/src/main/scala/org/llm4s/toolapi/builtin/filesystem/ListDirectoryTool.scala]: This still uses `toOption.getOrElse` for parameter defaults. Please keep this in explicit Result/Either transformation style so defaults do not bypass typed validation context. Principle: do not bypass typed error channels with option unwrapping helpers.

**Comment by im-vedant** [comment]
@rorygraves Could you review it?

File: modules/core/src/test/scala/org/llm4s/toolapi/builtin/ShellToolsSpec.scala [hunk 28]
```diff
@@ -76,87 +78,130 @@ class ShellToolsSpec extends AnyFlatSpec with Matchers {
...
+    ShellTool
+      .createSafe(config)
+      .fold(
+        e => fail(s"Tool creation failed: ${e.formatted}"),
+        tool => {
+          val params = ujson.Obj("command" -> "echo hello world")
+          val result = tool.handler(SafeParameterExtractor(params))
+
+          result.isRight shouldBe true
+          val shellResult = result.toOption.get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/builtin/ShellToolsSpec.scala]: `result.toOption.get` is still present in this updated spec.
Please replace with total Result handling (`fold`/pattern match) and explicit assertion failure paths.
Principle: no unsafe unwrapping in tests.

File: modules/core/src/test/scala/org/llm4s/mcp/MCPToolRegistryCacheSpec.scala [hunk 29]
```diff
@@ -45,45 +46,60 @@ class MCPToolRegistryCacheSpec extends AnyFlatSpec with Matchers {
...
+          localTools = Seq(tool),
+          cacheTTL = 1.minute,
+          initializeOnStartup = false
+        )
+
+        val request = ToolCallRequest("test_tool", ujson.Obj("input" -> "hello"))
+        val result  = registry.execute(request)
+
+        result.isRight shouldBe true
+        result.toOption.get("value").str shouldBe "result"
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/mcp/MCPToolRegistryCacheSpec.scala]: Same issue here: `toOption.get` and `left.toOption.get` are still unsafe.
Please use explicit Left/Right assertions with descriptive fail messages.
Principle: avoid partial getters in tests so failures stay diagnosable.

**Review by vim89 — CHANGES_REQUESTED** [review]
Request changes.
Intent is valid and roadmap-aligned: moving tool construction to Result improves API safety and production reliability.
Most earlier blockers are addressed (compat wrappers, structured llm cause, O(n) handoff tool accumulation, max_entries sample key).
Still open in this head: new test code keeps unsafe partial unwraps ( / ) in MCP and Shell specs; this repeats previously flagged style and weakens failure diagnostics.
Build checks are green, and codecov patch is passing; I did not run tests or build locally.
Please close these remaining unwrap findings, then this should be ready for final pass.

File: modules/core/src/test/scala/org/llm4s/toolapi/ToolRegistrySpec.scala [hunk 30]
```diff
@@ -82,228 +84,302 @@ class ToolRegistrySpec extends AnyFlatSpec with Matchers {
...
-    result.isLeft shouldBe true
-    result.left.getOrElse(fail()).getMessage should include("not a recognized tool")
+    createAddTool().fold(
+      e => fail(s"Tool creation failed: ${e.formatted}"),
+      addTool => {
+        val registry = new ToolRegistry(Seq(addTool))
+        val request  = ToolCallRequest("unknown_function", ujson.Obj())
+        val result   = registry.execute(request)
+        result.isLeft shouldBe true
+        result.left.getOrElse(fail()).getMessage should include("not a recognized tool")
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/ToolRegistrySpec.scala]: `left.getOrElse(fail())` still bypasses explicit typed failure handling. Please switch to fold/match so error assertions remain deterministic and descriptive. Principle: keep monadic error channels explicit in tests.

File: modules/core/src/test/scala/org/llm4s/agent/AgentToolCallingMultiProviderTest.scala [hunk 31]
```diff
@@ -48,141 +49,146 @@ class AgentToolCallingMultiProviderTest extends AnyFlatSpec with Matchers with M
...
-      contentOpt = Some("I've added the sword to your inventory."),
-      toolCalls = Seq.empty
-    )
+        (mockClient.complete _)
+          .expects(*, *)
+          .returning(Right(step1Completion))
+          .once()
+
+        // Run step 1 - should get tool call request
+        val stateAfterStep1 = agent.runStep(initialState).getOrElse(fail("Step 1 failed"))
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/agent/AgentToolCallingMultiProviderTest.scala]: This still uses Result fallback unwrapping via `getOrElse(fail(...))`. Please use explicit fold/pattern-match so the failing branch stays typed and intentional. Principle: tests should avoid partial/fallback unwrapping and keep error paths explicit.

File: modules/core/src/test/scala/org/llm4s/toolapi/ToolRegistrySpec.scala [hunk 32]
```diff
@@ -82,228 +84,302 @@ class ToolRegistrySpec extends AnyFlatSpec with Matchers {
...
+    val result = for {
+      addTool  <- createAddTool()
+      echoTool <- createEchoTool()
+    } yield {
+      val registry = new ToolRegistry(Seq(addTool, echoTool))
+      val tools    = registry.getOpenAITools()
+
+      tools.arr should have size 2
+
+      val addToolJson = tools.arr.find(t => t("function")("name").str == "add").get
```
Comment (vim89) [inline modules/core/src/test/scala/org/llm4s/toolapi/ToolRegistrySpec.scala]: This line reintroduces partial extraction with `.get`. Please replace with explicit Option handling and a clear fail message carrying context. Principle: no unsafe partial getters in tests.

**Review by vim89 — CHANGES_REQUESTED** [review]
Request changes: direction is good and most earlier blockers are now addressed, including safe API migration, linear handoff accumulation, and preserving structured llm cause in assistant errors.
Remaining blocker is still test safety and idiomatic consistency: updated specs continue using partial/fallback unwrapping patterns like `.get`, `left.getOrElse(fail())`, and similar shortcuts.
Please convert these to explicit fold or pattern-match assertions so failure branches stay typed and diagnosable.
Roadmap and architecture alignment is positive, but merge should wait until these quality gaps are closed.
I did not run tests or build locally.

**Comment by vim89** [comment]
@claude
