### PR TITLE
Fix missing EnhancedTracingExample and BuiltinTools.development docs

### LINKED ISSUE #455: Fix Documentation/Samples Mismatch: EnhancedTracingExample and BuiltinTools.development()
## Problem Description

I found two documentation inconsistencies that could confuse new users:

### Issue 1: Missing `EnhancedTracingExample` Sample

The documentation at `docs/examples/index.md` references a sample file that doesn't exist:

**Location:** `docs/examples/index.md` (lines 126-143)

The docs include:

- A link to `EnhancedTracingExample.scala`
- A run command: `sbt "samples/runMain org.llm4s.samples.basic.EnhancedTracingExample"`
- Description of what it demonstrates

However, the file `modules/samples/src/main/scala/org/llm4s/samples/basic/EnhancedTracingExample.scala` does not exist in the repository.

**Impact:** Users following the example gallery will encounter a broken link and a non-functional run command, leading to confusion and reduced trust in the documentation.

### Issue 2: `BuiltinTools.development()` Documentation Mismatch

The docstring for `BuiltinTools.development()` claims it includes "Web search", but the implementation does not include any search tools.

**Location:** `modules/core/src/main/scala/org/llm4s/toolapi/builtin/BuiltinTools.scala` (lines 88-103)

**Documentation says:**

```scala
/**
 * Development tools with full read/write and shell access.
 *
 * Includes:
 * - All core utilities
 * - Web search          <-- Claims web search is included
 * - Full HTTP access
 * ...
 */
```

**Implementation shows:**

```scala
def development(...): Seq[ToolFunction[_, _]] = {
  // ...
  core ++ Seq(
    HTTPTool.tool,
    ReadFileTool.create(fileConfig),
    ListDirectoryTool.create(fileConfig),
    FileInfoTool.create(fileConfig),
    WriteFileTool.create(writeConfig),
    ShellTool.create(shellConfig)
  )
  // No DuckDuckGoSearchTool or BraveSearchTool included
}
```

**Impact:** Users expecting web search to be available via `BuiltinTools.development()` will find it missing, requiring them to manually add search tools (as seen in `ResearcherAgentExample.scala`).

### For Issue 1: EnhancedTracingExample

**Option A (Recommended):** Remove the `EnhancedTracingExample` section from `docs/examples/index.md` since there are already working tracing examples (`BasicLLMCallingWithTrace`, `TracingExample`, `LangfuseSampleTraceRunner`).

**Option B:** Create the missing `EnhancedTracingExample.scala` sample file that matches the documented description (detailed trace information, agent state tracking, token usage analysis, multi-level tracing).

**Option C:** Replace the `EnhancedTracingExample` entry with a link to an existing tracing example that demonstrates similar functionality.

### For Issue 2: BuiltinTools.development()

**Option A (Recommended):** Update the docstring to remove the "Web search" claim, since search tools require separate configuration (API keys, etc.) and are not included by default.

**Option B:** Add optional search tool support to `development()` method (e.g., `development(..., includeSearch: Boolean = false)` or via a separate `developmentWithSearch()` method), then update the docstring accordingly.

## Verification Steps

To verify these issues:

1. **Check for EnhancedTracingExample:**

   ```bash
   find modules/samples -name "*EnhancedTracing*"
   # Returns: (no results)
   ```

2. **Check BuiltinTools.development() implementation:**
   ```bash
   grep -A 20 "def development" modules/core/src/main/scala/org/llm4s/toolapi/builtin/BuiltinTools.scala
   # Shows no search tools in the returned Seq
   ```

## Additional Context

- This appears to be a documentation maintenance issue rather than a code bug
- Both issues are straightforward to fix and would improve the developer experience
- The existing codebase has working examples for tracing (`TracingExample.scala`, `BasicLLMCallingWithTrace.scala`) and search tools are available separately (`DuckDuckGoSearchTool`, `BraveSearchTool`)

## Labels

- `documentation`
- `good first issue`
- `help wanted`

---

**Note:** This is my first contribution to LLM4S. I'm happy to implement the fixes myself if maintainers prefer Option A for both issues, or I can wait for guidance on which approach is preferred.

### PR DESCRIPTION
**Pull request by Piyush-t24**
This PR fixes two documentation mismatches:

- Adds the missing EnhancedTracingExample sample referenced in the docs.
- Updates BuiltinTools.development Scaladoc to remove the incorrect “Web search” claim.

Verified by running:
sbt "samples/runMain org.llm4s.samples.basic.EnhancedTracingExample"

Fixes #455

### CODE REVIEW

**Comment by vim89** [comment]
Holistic view: fixing missing docs and examples improves trust in the reference material.
Please verify examples compile and API names exactly match current core surfaces.
Good maintenance value and low risk.

**Comment by Piyush-t24** [comment]
@vim89 Sir, Thanks for the review!  
I’ve verified that the new EnhancedTracingExample compiles and runs successfully, and that all API names match the current core surfaces.

Tested via:
sbt "samples/runMain org.llm4s.samples.basic.EnhancedTracingExample"

Appreciate you taking a look!

File: modules/samples/src/main/scala/org/llm4s/samples/basic/EnhancedTracingExample.scala [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+      case Left(error) =>
+        // Trace error and log it
+        tracer.traceError(new RuntimeException(error.formatted))
+        logger.error("LLM error in EnhancedTracingExample: {}", error.formatted)
+    }
+
+    // Trace end of conversation
+    tracer.traceEvent("EnhancedTracingExample: conversation finished")
+  }
+}
```
Comment (vim89) [inline modules/samples/src/main/scala/org/llm4s/samples/basic/EnhancedTracingExample.scala]: Nit: please add a trailing newline at end of file to match repository file hygiene and avoid noisy diffs in follow-up edits.

**Comment by Piyush-t24** [comment]
@vim89 Sir, Thanks for catching that — added a trailing newline to the file.

**Comment by Piyush-t24** [comment]
Thanks @rorygraves  🙏
Formatting change looks good. I had already verified the example runs locally with Ollama.

**Comment by rorygraves** [comment]
Thanks @Piyush-t24
