### PR TITLE
fix: correctly report truncation status and total matches in search r…

### LINKED ISSUE #714: [BUG] workspaceRunner: searchFiles reports isTruncated incorrectly when result cap is hit
### Description

`searchFiles` can return `isTruncated = false` even when additional matches exist beyond the configured result cap.

The implementation stops scanning when `matches.size` reaches `maxSearchResults`, but `isTruncated` is computed from `totalMatches > maxSearchResults`. Because counting also stops at the cap, `totalMatches` often does not exceed the cap, so truncation is under-reported.

### Steps to Reproduce

1. Prepare a workspace directory containing more than 100 lines/files matching the same query string.
2. Call `searchFiles` with that query (default cap is `maxSearchResults = 100`).
3. Inspect `SearchFilesResponse`.
4. Observe `matches.size == 100` but `isTruncated == false` in cases where there are clearly more matches.

### Expected Behavior

When scanning stops due to the result cap, `isTruncated` should be `true`.

### Actual Behavior

`isTruncated` is often `false` even though additional matches exist beyond the cap.

### Impact Areas

- [x] API / Compatibility
- [ ] Security / Privacy
- [x] Reliability / Availability
- [ ] Performance
- [ ] Documentation
- [ ] Unsure

### Error Logs / Stack Trace

```scala
No crash/stack trace. Logical response inconsistency in returned metadata.
```

### Scala Version

3.7.1

### JDK Version

JDK 21

### Operating System

Windows

### OS Details (if other)

Windows 11

### LLM Provider

Other (please specify below)

### Model Information

N/A

### LLM4S Version

main branch (local checkout)

### Code Snippet

```scala
val resp = workspace.searchFiles(
  paths = List("."),
  query = "needle",
  searchType = "literal",
  recursive = Some(true)
)

println(s"matches=${resp.matches.size}, total=${resp.totalMatches}, truncated=${resp.isTruncated}")
```

### Configuration (if relevant)

```bash
# default workspace limits
maxSearchResults = 100
```

### Additional Context

Related code:
- modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala:515
- modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala:544

Suggested fix direction: track whether scan terminated early due to cap (separate boolean), and use that for `isTruncated`.

### Pre-submission Checklist

- [x] I have searched existing issues and found no duplicates
- [x] I have provided all required environment information
- [x] I have provided a minimal reproducible example
- [x] I have anonymized any sensitive data (API keys, etc.)

### PR DESCRIPTION
**Pull request by AMAN-sharma07**
## What does this PR do?
Fixes an inconsistency in WorkspaceAgentInterfaceImpl.searchFiles where the response flag
isTruncated could be false even though more matching lines existed beyond the configured
result cap. The previous implementation stopped scanning when matches.size hit the limit
and then computed truncation by comparing a capped totalMatches to the limit – which never
happened.
This change keeps counting hits after the cap, introduces a boolean flag to track early exit,
and returns it as isTruncated. The unit test was strengthened to verify both the flag and the
actual total match count. 

## Related issue
fixes #714 

## How was this tested?
Existing **WorkspaceAgentInterfaceImplTest** suite was enhanced with a new case that
creates a workspace file containing five occurrences and runs a tiny‑limit interface.
Verified that **matches.size** equals the cap, **isTruncated**  is true, and **totalMatches**
reflects the real number of occurrences.
All other workspace tests continue to pass.
(Locally I ran **sbt+test** to ensure cross‑version success – formatting already matches.)

## Checklist

- [ ] I have read the [Contributing Guide](https://llm4s.org/reference/contributing)
- [ ] PR is small and focused — one change, one reason
- [ ] `sbt scalafmtAll` — code is formatted
- [ ] `sbt +test` — tests pass on both Scala 2.13 and 3.x
- [ ] New code includes tests
- [ ] No unrelated changes included (branched from `main`, not from another PR)
- [ ] Commit messages explain the "why"

### CODE REVIEW

**Comment by AMAN-sharma07** [comment]
@kannupriyakalra @rorygraves a review is requested

File: modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala [hunk 1]
```diff
@@ -502,28 +502,44 @@ class WorkspaceAgentInterfaceImpl(
     // Search in files
     var matches      = List.empty[SearchMatch]
     var totalMatches = 0
+    var truncated    = false
 
-    for (file <- filesToSearch if matches.size < defaultLimits.maxSearchResults) {
+    // we always walk every file so that we can correctly report whether the
+    // search stopped early due to the hard cap; we still stop accumulating
+    // `matches` once the cap is reached in order to honour the limit, but we
+    // keep counting hits so callers can see the true total if desired.
```
Comment (rorygraves) [inline modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala]: **Medium — Performance regression**: The old code short-circuited both the file loop and the line loop once the cap was hit. The new code iterates **every line of every file** even after the cap is reached, just to count total matches. For workspaces with many large files this could be significantly slower. The `totalMatches` count is informational — it's not worth scanning an entire workspace for it.

**Suggestion**: Consider keeping the old outer-loop early-exit and simplifying the truncation check to `isTruncated = totalMatches > matches.size` (which is always correct). Alternatively, add a secondary cap on total scanning. Either approach preserves the bug fix while avoiding the performance regression.

File: modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala [hunk 2]
```diff
@@ -502,28 +502,44 @@ class WorkspaceAgentInterfaceImpl(
...
-
-            matches = matches :+ SearchMatch(
-              path = relativePath,
-              line = lineNumber,
-              matchText = line,
-              contextBefore = beforeContext,
-              contextAfter = afterContext
-            )
+            if (matches.size < defaultLimits.maxSearchResults) {
+              val lineNumber    = lineIndex + 1
```
Comment (rorygraves) [inline modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala:522]: **Low — Redundant `truncated` flag**: The `truncated` variable is set in two places but could be removed entirely. Since you're already tracking `totalMatches` and `matches.size`, you can compute truncation at the end:

```scala
isTruncated = totalMatches > matches.size
```

This is simpler and impossible to get wrong.

File: modules/workspace/workspaceRunner/src/test/scala/org/llm4s/runner/WorkspaceAgentInterfaceImplTest.scala [hunk 3]
```diff
@@ -1,6 +1,7 @@
 package org.llm4s.runner
```
Comment (rorygraves) [inline modules/workspace/workspaceRunner/src/test/scala/org/llm4s/runner/WorkspaceAgentInterfaceImplTest.scala:2]: **Low — Redundant import**: `org.llm4s.shared._` on the line above already includes `WorkspaceSandboxConfig`. This explicit import can be removed.

File: modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala (hunk 1 above)
Comment (AMAN-sharma07) [reply modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala]: Thanks for pointing this out — you’re right about the potential performance regression.
I restored early exit behavior in both file and line loops and switched to cap+1 detection to avoid scanning the entire workspace. This preserves the truncation fix while preventing the performance regression. 
Let me know if you'd like any further refinements.

File: modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala (hunk 2 above)
Comment (AMAN-sharma07) [reply modules/workspace/workspaceRunner/src/main/scala/org/llm4s/runner/WorkspaceAgentInterfaceImpl.scala:522]: Good point — I’ve removed the redundant truncated flag and now compute `isTruncated` at the end using `totalMatches` > `matches.size`. This keeps the logic simpler and avoids duplicate state.

File: modules/workspace/workspaceRunner/src/test/scala/org/llm4s/runner/WorkspaceAgentInterfaceImplTest.scala (hunk 3 above)
Comment (AMAN-sharma07) [reply modules/workspace/workspaceRunner/src/test/scala/org/llm4s/runner/WorkspaceAgentInterfaceImplTest.scala:2]: Removed the redundant explicit import — the wildcard import already covers it.

**Review by rorygraves — APPROVED** [review]
## Re-Review: PR #779

All 3 issues from the previous review are resolved:

| # | Issue | Status |
|---|-------|--------|
| 1 | **Medium**: Performance regression (scanning entire workspace for totalMatches) | **Fixed** — restored early exit with `done` flag; only scans one match past the cap |
| 2 | **Low**: Redundant `truncated` flag | **Fixed** — removed; now uses `isTruncated = totalMatches > matches.size` |
| 3 | **Low**: Redundant `WorkspaceSandboxConfig` import in test | **Fixed** — removed |

The cap+1 approach is a clean solution — it correctly detects truncation while avoiding a full workspace sweep, and the test accurately documents the guarantee (`totalMatches` is `maxSearchResults + 1` when truncated, not the true total). Nice work.

Approving.
